### ISSUE TITLE
stimuli

### ISSUE THREAD

**Issue by zits69** [janfreyberg/binocular-rivalry#2]
Hi Jan
Amazing script, thank you for sharing!
Would you be able to upload the .jpgs for the scripts? I realize i am being lazy and could just make some, but if it's not too much trouble it would just be easier to see how you had made it originally.
Many thanks!
z

**Comment by janfreyberg** [comment]
Yep, no prob - see here: https://github.com/janfreyberg/binocular-rivalry/commit/113f8d0715d585edb0fdc95f8fc646bbf8b17579

**Comment by zits69** [comment]
ah! you are great thank you!
